v7.1.0
* Add option to install Memcached Server
* Add memcached pecl extensions into PHP
* Remove "ENABLED" from OPTIONS
* APC is now installed via PECL repository
* The update_apc script is removed (in favour of `pecl upgrade`)
* Suhosin is now removed completely
* Updated init scripts for NginX and PHP

Signed-off-by: Vlad <vg@vladgh.com>

diff --git a/init_files/nginx b/init_files/nginx
--- a/init_files/nginx
+++ b/init_files/nginx
@@ -1,73 +1,112 @@
-#! /bin/sh
+#!/bin/sh
 ### BEGIN INIT INFO
 # Provides:          nginx
-# Required-Start:    $remote_fs $syslog
-# Required-Stop:     $remote_fs $syslog
+# Required-Start:    $network $remote_fs $local_fs
+# Required-Stop:     $network $remote_fs $local_fs
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: nginx init.d script for Ubuntu.
-# Description:       nginx init.d script for Ubuntu.
+# Short-Description: Stop/start nginx
 ### END INIT INFO
 
-# Import init-functions
+# Author: Sergey Budnevitch <sb@nginx.com>
+
+INSTALL_DIR='@DESTINATION_DIR@/nginx'
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC=nginx
+NAME=nginx
+CONFIG_FILE=/etc/nginx/nginx.conf
+DAEMON="${INSTALL_DIR}/sbin/${NAME}"
+DAEMON_OPTS="-c $CONFIG_FILE"
+PIDFILE=/var/run/${NAME}.pid
+SCRIPTNAME=/etc/init.d/${NAME}
+
+[ -x $DAEMON ] || exit 0
+
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+
+. /lib/init/vars.sh
+
 . /lib/lsb/init-functions
 
-INSTALL_DIR="/opt/nginx"
 
-### Location of nginx binary. Change path as neccessary
-DAEMON="$INSTALL_DIR/sbin/nginx"
-### Location of configuration file. Change path as neccessary
-CONFIG_FILE=/etc/nginx/nginx.conf
+do_start()
+{
+  # Check if the ULIMIT is set in /etc/default/nginx
+  if [ -n "$ULIMIT" ]; then
+    # Set the ulimits
+    ulimit $ULIMIT
+  fi
+  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+    $DAEMON_OPTS \
+    || return 2
+}
 
-DAEMON_OPTS="-c $CONFIG_FILE"
-NAME=nginx
-DESC="Web Server"
-PIDFILE=/var/run/$NAME.pid
-SCRIPTNAME=/etc/init.d/$NAME
+do_stop()
+{
+  # Return
+  #   0 if daemon has been stopped
+  #   1 if daemon was already stopped
+  #   2 if daemon could not be stopped
+  #   other if a failure occurred
+  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+  RETVAL="$?"
+  rm -f $PIDFILE
+  return "$RETVAL"
+}
 
-test -x $DAEMON || exit 0
-
-set -e
+do_reload() {
+  #
+  start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+  return 0
+}
 
 case "$1" in
   start)
-    log_daemon_msg "Starting $DESC" $NAME
-    if ! start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS ; then
-      log_end_msg 1
-    else
-      log_end_msg 0
-    fi
+    log_daemon_msg "Starting $DESC " "$NAME"
+    do_start
+    case "$?" in
+    0|1) log_end_msg 0 ;;
+    2) log_end_msg 1 ;;
+  esac
   ;;
   stop)
-    log_daemon_msg "Stopping $DESC" $NAME
-    if start-stop-daemon --quiet --stop --oknodo --retry 30 --pidfile $PIDFILE --exec $DAEMON; then
-      rm -f $PIDFILE
-      log_end_msg 0
-    else
-      log_end_msg 1
-    fi
+  log_daemon_msg "Stopping $DESC" "$NAME"
+  do_stop
+  case "$?" in
+    0|1) log_end_msg 0 ;;
+    2) log_end_msg 1 ;;
+  esac
   ;;
-  reload)
-    log_daemon_msg "Reloading $DESC configuration" $NAME
-    if start-stop-daemon --stop --signal 2 --oknodo --retry 30 --quiet --pidfile $PIDFILE --exec $DAEMON; then
-    if start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS ; then
-      log_end_msg 0
-    else
-      log_end_msg 1
-    fi
-    else
-      log_end_msg 1
-    fi
+  status)
+       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+       ;;
+  reload|force-reload)
+  log_daemon_msg "Reloading $DESC" "$NAME"
+  do_reload
+  log_end_msg $?
   ;;
   restart|force-reload)
-    $0 stop
-    sleep 1
-    $0 start
+  log_daemon_msg "Restarting $DESC" "$NAME"
+  do_stop
+  case "$?" in
+    0|1)
+    do_start
+    case "$?" in
+      0) log_end_msg 0 ;;
+      1) log_end_msg 1 ;; # Old process is still running
+      *) log_end_msg 1 ;; # Failed to start
+    esac
+    ;;
+    *)
+      # Failed to stop
+    log_end_msg 1
+    ;;
+  esac
   ;;
   *)
-  echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-  exit 1
+  echo "Usage: $SCRIPTNAME {start|stop|status|restart|reload|force-reload}" >&2
+  exit 3
   ;;
 esac
 
-exit 0
+:
diff --git a/init_files/php5-fpm b/init_files/php5-fpm
--- a/init_files/php5-fpm
+++ b/init_files/php5-fpm
@@ -1,136 +1,178 @@
-#! /bin/sh
-
+#!/bin/sh
 ### BEGIN INIT INFO
-# Provides:          php-fpm
+# Provides:          php-fpm php5-fpm
 # Required-Start:    $remote_fs $network
 # Required-Stop:     $remote_fs $network
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: starts php-fpm
-# Description:       starts the PHP FastCGI Process Manager daemon
+# Short-Description: starts php5-fpm
+# Description:       Starts PHP5 FastCGI Process Manager Daemon
 ### END INIT INFO
 
+# Author: Ondrej Sury <ondrej@debian.org>
 
-php_fpm_BIN=@DESTINATION_DIR@/php5/sbin/php-fpm
-php_fpm_CONF=/etc/php5/php-fpm.conf
-php_fpm_PID=/var/run/php-fpm.pid
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="PHP5 FastCGI Process Manager"
+NAME=php-fpm
+DAEMON=@DESTINATION_DIR@/php5/sbin/${NAME}
+DAEMON_ARGS="--fpm-config /etc/php5/${NAME}.conf"
+PIDFILE=/var/run/${NAME}.pid
+TIMEOUT=30
+SCRIPTNAME=/etc/init.d/${NAME}
 
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
 
-php_opts="--fpm-config $php_fpm_CONF"
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
 
-wait_for_pid () {
-	try=0
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
+. /lib/lsb/init-functions
 
-	while test $try -lt 35 ; do
+#
+# Function to check the correctness of the config file
+#
+do_check()
+{
+    [ "$1" != "no" ] && $DAEMON $DAEMON_ARGS -t 2>&1 | grep -v "\[ERROR\]"
+    FPM_ERROR=$($DAEMON $DAEMON_ARGS -t 2>&1 | grep "\[ERROR\]")
 
-		case "$1" in
-			'created')
-			if [ -f "$2" ] ; then
-				try=''
-				break
-			fi
-			;;
+    if [ -n "${FPM_ERROR}" ]; then
+  echo "Please fix your configuration file..."
+  $DAEMON $DAEMON_ARGS -t 2>&1 | grep "\[ERROR\]"
+  return 1
+    fi
+    return 0
+}
 
-			'removed')
-			if [ ! -f "$2" ] ; then
-				try=''
-				break
-			fi
-			;;
-		esac
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+  # Return
+  #   0 if daemon has been started
+  #   1 if daemon was already running
+  #   2 if daemon could not be started
+  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+    || return 1
+  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+    $DAEMON_ARGS 2>/dev/null \
+    || return 2
+  # Add code here, if necessary, that waits for the process to be ready
+  # to handle requests from services started subsequently which depend
+  # on this one.  As a last resort, sleep for some time.
+}
 
-		echo -n .
-		try=`expr $try + 1`
-		sleep 1
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+  # Return
+  #   0 if daemon has been stopped
+  #   1 if daemon was already stopped
+  #   2 if daemon could not be stopped
+  #   other if a failure occurred
+  start-stop-daemon --stop --quiet --retry=QUIT/$TIMEOUT/TERM/5/KILL/5 --pidfile $PIDFILE --name $NAME
+  RETVAL="$?"
+  [ "$RETVAL" = 2 ] && return 2
+  # Wait for children to finish too if this is a daemon that forks
+  # and if the daemon is only ever run from this initscript.
+  # If the above conditions are not satisfied then add some other code
+  # that waits for the process to drop all resources that could be
+  # needed by services started subsequently.  A last resort is to
+  # sleep for some time.
+  start-stop-daemon --stop --quiet --oknodo --retry=0/30/TERM/5/KILL/5 --exec $DAEMON
+  [ "$?" = 2 ] && return 2
+  # Many daemons don't delete their pidfiles when they exit.
+  rm -f $PIDFILE
+  return "$RETVAL"
+}
 
-	done
-
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+  #
+  # If the daemon can reload its configuration without
+  # restarting (for example, when it is sent a SIGHUP),
+  # then implement that here.
+  #
+  start-stop-daemon --stop --signal USR2 --quiet --pidfile $PIDFILE --name $NAME
+  return 0
 }
 
 case "$1" in
-	start)
-		echo -n "Starting php-fpm "
-
-		$php_fpm_BIN $php_opts
-
-		if [ "$?" != 0 ] ; then
-			echo " failed"
-			exit 1
-		fi
-
-		wait_for_pid created $php_fpm_PID
-
-		if [ -n "$try" ] ; then
-			echo " failed"
-			exit 1
-		else
-			echo " done"
-		fi
-	;;
-
-	stop)
-		echo -n "Gracefully shutting down php-fpm "
-
-		if [ ! -r $php_fpm_PID ] ; then
-			echo "warning, no pid file found - php-fpm is not running ?"
-			exit 1
-		fi
-
-		kill -QUIT `cat $php_fpm_PID`
-
-		wait_for_pid removed $php_fpm_PID
-
-		if [ -n "$try" ] ; then
-			echo " failed. Use force-quit"
-			exit 1
-		else
-			echo " done"
-		fi
-	;;
-
-	force-quit)
-		echo -n "Terminating php-fpm "
-
-		if [ ! -r $php_fpm_PID ] ; then
-			echo "warning, no pid file found - php-fpm is not running ?"
-			exit 1
-		fi
-
-		kill -TERM `cat $php_fpm_PID`
-
-		wait_for_pid removed $php_fpm_PID
-
-		if [ -n "$try" ] ; then
-			echo " failed"
-			exit 1
-		else
-			echo " done"
-		fi
-	;;
-
-	restart)
-		$0 stop
-		$0 start
-	;;
-
-	reload)
-
-		echo -n "Reload service php-fpm "
-
-		if [ ! -r $php_fpm_PID ] ; then
-			echo "warning, no pid file found - php-fpm is not running ?"
-			exit 1
-		fi
-
-		kill -USR2 `cat $php_fpm_PID`
-
-		echo " done"
-	;;
-
-	*)
-		echo "Usage: $0 {start|stop|force-quit|restart|reload}"
-		exit 1
-	;;
-
+    start)
+  [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+  do_check $VERBOSE
+  case "$?" in
+      0)
+    do_start
+    case "$?" in
+        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
+    ;;
+      1) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+  esac
+  ;;
+    stop)
+  [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+  do_stop
+  case "$?" in
+    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+  esac
+  ;;
+    status)
+        status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+        ;;
+    check)
+        do_check yes
+  ;;
+    reload|force-reload)
+  log_daemon_msg "Reloading $DESC" "$NAME"
+  do_reload
+  log_end_msg $?
+  ;;
+    reopen-logs)
+  log_daemon_msg "Reopening $DESC logs" $NAME
+  if start-stop-daemon --stop --signal USR1 --oknodo --quiet \
+      --pidfile $PIDFILE --exec $DAEMON
+  then
+      log_end_msg 0
+  else
+      log_end_msg 1
+  fi
+  ;;
+    restart)
+  log_daemon_msg "Restarting $DESC" "$NAME"
+  do_stop
+  case "$?" in
+    0|1)
+    do_start
+    case "$?" in
+      0) log_end_msg 0 ;;
+      1) log_end_msg 1 ;; # Old process is still running
+      *) log_end_msg 1 ;; # Failed to start
+    esac
+    ;;
+    *)
+      # Failed to stop
+    log_end_msg 1
+    ;;
+  esac
+  ;;
+    *)
+  echo "Usage: $SCRIPTNAME {start|stop|status|restart|reload|force-reload}" >&2
+  exit 1
+    ;;
 esac
+
+:
